directive @hasPermissions(
  role: [Permission!]
) on FIELD_DEFINITION | INPUT_FIELD_DEFINITION

enum Permission {
  EMOTE_CREATE
  EMOTE_EDIT
  EMOTESET_CREATE
  EMOTESET_EDIT

  REPORT_CREATE
  SEND_MESSAGES

  FEATURE_ZEROWIDTH_EMOTE_TYPE
  FEATURE_PROFILE_PICTURE_ANIMATION

  MANAGE_BANS
  MANAGE_ROLES
  MANAGE_REPORTS
  MANAGE_USERS
  EMOTE_EDIT_ANY
  EMOTESET_EDIT_ANY
  BYPASS_PRIVACY

  SUPER_ADMINISTRATOR
  MANAGE_NEWS
  MANAGE_STACK
  MANAGE_COSMETICS
}
