
type Ban {
    id: String!
    # The user affected by this ban
    victim: User
    # The user who created this ban
    actor: User
    # The reason for the ban
    reason: String!
    # The effects this ban has
    effects: [BanEffect!]!
    # The date on which the ban expire.
    # If this is zero, the ban is considered permanent
    expire_at: String!
}

enum BanEffect {
    NO_PERMISSIONS
    NO_AUTH
    NO_OWNERSHIP
    MEMORY_HOLE
    IP_BLOCKED
}
