type Query {
	# user(id: String!): User
	emotes(
		query: String!,
		limit: Int,
		after_id: String,
		before_id: String,
		sort: Sort
		# providers: [Provider!],
	): [EmoteTest]!
}

# Sorting cursor, binding a specific order to a value
input Sort {
	value: String!
	order: SortOrder!
}

# The order with which sorting should occur, either ASCENDING or DESCENDING
enum SortOrder {
	ASCENDING
	DESCENDING
}
