
type Report {
	id: String!
	target_kind: TargetKind!
	target: User
	reporter: User
	subject: String!
	body: String!
	priority: Int!
	assignees: [User]!
	status: ReportStatus!
	created_at: String!
}

enum TargetKind {
	EMOTE
	USER
}

enum ReportStatus {
	OPEN
	ASSIGNED
	CLOSED
}