type EmoteSet {
  id: ObjectID!
  name: String!
  tags: [String!]!
  emotes: [ActiveEmote!]!
  emote_slots: Int!
  owner: User
}

type ActiveEmote {
  id: ObjectID!
  name: String!
  flags: Int!
  timestamp: Time!
  emote: Emote
}

extend type Mutation {
  createEmoteSet(data: CreateEmoteSetInput!): EmoteSet
    @hasPermissions(role: [EMOTESET_CREATE])
}

input CreateEmoteSetInput {
  name: String!
  privileged: Boolean @hasPermissions(role: [SUPER_ADMINISTRATOR])
}
