directive @hasPermissions(role: [Permission!]) on FIELD_DEFINITION

enum Permission {
  CreateEmote
  EditEmote
  SetChannelEmote

  ReportCreate
  SendMessages

  FeatureZeroWidthEmoteType
  FeatureProfilePictureAnimation

  ManageBans
  ManageRoles
  ManageReports
  ManageUsers
  EditAnyEmote
  EditAnyEmoteSet
  BypassPrivacy

  SuperAdministrator
  ManageNews
  ManageStack
  ManageCosmetics
}
