on:
  push:
    branches:
      - master
      - stage
      - dev
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [1.17]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck

      - name: Lint
        run: staticcheck ./...
